version: '3'

services:
    # vigil-frontend:
    #     build: ./vigil/frontend
    #     container_name: vigil-frontend
    #     command: ["pnpm", "dev"]
    #     environment:
    #         NEXT_PUBLIC_GITHUB_TOKEN: ${NEXT_PUBLIC_GITHUB_TOKEN}
    #         NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    #     ports:
    #         - 3000:3000
    #     depends_on:
    #         - vigil-backend

    vigil-backend:
        build: ./vigil/backend
        container_name: vigil-backend
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--ssl-keyfile", "/code/key.pem", "--ssl-certfile", "/code/cert.pem"]
        environment:
            VIGIL_REDIS_URL: ${VIGIL_REDIS_URL}
            LIBRARIES_API_KEY: ${LIBRARIES_API_KEY}
        ports:
            - 5000:5000
        depends_on:
            - vigil-redis  

    # vigil-cli:
    #     build: ./vigil/cli
    #     container_name: vigil-cli

    vigil-redis: 
        image: redis:7.2.2-alpine
        container_name: vigil-redis
        ports:
            - 6379:6379
        volumes:
            - vigil-redis-data:/data

    vigil-prometheus:
        image: prom/prometheus
        container_name: vigil-prometheus
        ports:
            - 9090:9090
        volumes:
            - ./vigil/infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'

    vigil-grafana:
        image: grafana/grafana
        container_name: vigil-grafana
        ports:
            - 8080:3000
        volumes:
            - grafana_data:/var/lib/grafana

volumes:
    vigil-redis-data:
        driver: local

    grafana_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./grafana_data
