version: '3'

services:
    vigil-frontend:
        build: ./vigil/frontend
        container_name: vigil-frontend
        command: ["pnpm", "dev"]
        environment:
            NEXT_PUBLIC_GITHUB_TOKEN: ${NEXT_PUBLIC_GITHUB_TOKEN}
            NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        ports:
            - 3000:3000
        depends_on:
            - vigil-backend

    vigil-backend:
        build: ./vigil/backend
        container_name: vigil-backend
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
        environment:
            VIGIL_ES_URL: ${VIGIL_ES_URL}
            VIGIL_LIBRARIES_API_KEY: ${VIGIL_LIBRARIES_API_KEY}
        ports:
            - 5000:5000
        depends_on:
            - vigil-es

    vigil-cli:
        build: ./vigil/cli
        container_name: vigil-cli

    vigil-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: vigil-es
        environment:
            - node.name=elasticsearch
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - vigil-esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

    vigil-kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        container_name: vigil-kibana
        environment:
            ELASTICSEARCH_URL: "http://vigil-es:9200"
        ports:
            - 5601:5601
        depends_on:
            - vigil-es

volumes:
    vigil-esdata:
        driver: local

networks:
    vigil-network:
