version: '3'

services:
    vigil-frontend:
        build: ./vigil/frontend
        container_name: vigil-frontend
        command: ["pnpm", "dev"]
        environment:
            NEXT_PUBLIC_GITHUB_TOKEN: ${NEXT_PUBLIC_GITHUB_TOKEN}
            NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        ports:
            - 3000:3000
        depends_on:
            - vigil-backend

    vigil-backend:
        build: ./vigil/backend
        container_name: vigil-backend
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
        environment:
            VIGIL_REDIS_URL: ${VIGIL_REDIS_URL}
        ports:
            - 5000:5000
        depends_on:
            - vigil-redis  

    vigil-cli:
        build: ./vigil/cli
        container_name: vigil-cli

    vigil-redis: 
        image: redis:7.2.2-alpine
        container_name: vigil-redis
        ports:
            - 6379:6379
        volumes:
            - vigil-redis-data:/data

volumes:
    vigil-redis-data:
        driver: local
