name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup virtual environment
        run: |
          pip install --upgrade pip
          python3.8 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV" $VIRTUAL_ENV

      - name: Install dependencies
        run: |
          source venv/bin/activate
          make install-dev

      - name: Start server
        run: |
          source venv/bin/activate
          make backend-start

      - name: Start frontend
        run: |
          source venv/bin/activate
          make frontend-start

      - name: Run tests
        run: |
          source venv/bin/activate
          make test
